---
cluster: 
  name: odyssey
  profile: lsf
  cores: 8
  delay: 10

dir: 
  results: results
  data: data
  meta: meta
  tmp: tmp

ref:
  - name: opossum
    ensembl_name: mdomestica_gene_ensembl
    file: ref/Monodelphis_domestica.BROADO5.61.cdna.all.fa
    url: ftp://ftp.ensembl.org/pub/release-67/fasta/monodelphis_domestica/cdna/Monodelphis_domestica.BROADO5.67.cdna.all.fa.gz

program:
  blast: blastn

experiment:
  name: potoroo

  - stage: blastn
    program: blastn
    

  - stage: filter_contigs
    program: filter_contigs.py

  run:
    [ blast ]
