- name: cutadapt
  program: cutadapt
  tag: cut
  expects: [fasta, fastq]
  produces: [fasta, fastq]

- name: tagdust
  program: tagdust
  tag: dusted
  expects: [fasta, fastq]
  produces: [fasta, fastq]

- name: fastqc
  program: fastqc
  requires: [-o]
  expects: [fastq, fq]
  produces: [zip]
